# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://juliansimioni.com
title: "Julian Simioni"
subtitle:
author: Julian Simioni
description: The words and code of Julian Simioni

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:
category_title_prefix: "Posts About "

safe: false

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
gems:
    - jekyll-redirect-from
    - jekyll/footnotes
    - jekyll-assets
    - jekyll-compass
    - jekyll-picture-tag

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments # default python pygments have been replaced by pygments.rb

excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: false       # Converts page and post titles to titlecase

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
# Disqus Comments
disqus_short_name: juliansimionisblog
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-35876353-1

assets:
  js_compressor: uglifier
  css_compressor: sass

picture:
  markup: "picture"
  output: ""
  presets:
    default:
      ppi: [1, 1.5, 2.0]
      attr:
        class: "gallery-pict"
        itemprop: "image"
      source_full:
        media: "(min-width: 830px)"
        width: "830"
      source_medium:
        media: "(min-width: 600px)"
        width: "600"
      source_default:
        width: "320"
    photo_6k_4k:
      ppi: [1, 1.5, 2.0]
      attr:
        class: "gallery-pict"
        itemprop: "image"
      source_4000:
        media: "(min-width: 4000px)"
        width: "4000"
      source_3000:
        media: "(min-width: 3000px)"
        width: "3000"
      source_2000:
        media: "kmin-width: 2000px)"
        width: "2000"
      source_1500:
        media: "(min-width: 1500px)"
        width: "1500"
      source_1000:
        media: "(min-width: 1000px)"
        width: "1000"
      source_900:
        media: "(min-width: 900px)"
        width: "900"
      source_800:
        media: "(min-width: 800px)"
        width: "800"
      source_400:
        media: "(min-width: 400px)"
        width: "400"
      source_default:
        width: "320"
