#!/bin/bash

set -ex

# location of blog files
blogroot="/var/www/localhost/htdocs"

current_date=$(date +"%Y-%m-%dT%H:%M:%SZ")

# archive current blog
ssh bloghost tar c \
  --exclude="$blogroot/back*" \
  --exclude="$blogroot/mu*" \
  -jpf \
  ./backup/blog-${current_date}.tar.bz2 $blogroot

# rsync over
rsync -avze ssh public/ bloghost:$blogroot
